### ISSUE TITLE
Cannot self-delegate

### ISSUE THREAD

**Issue by nodespace1** [e-money/treasury-delegations#39]
My validator (emoneyvaloper1amq83m7k9mhdd255epc68s5ucmc4tag6ywxq0p) was recently added to the whitelist. However, since the approval process took more than 2 months, I had undelegated the funds (some days prior to whitelisting) believing my request would not be approved. Now that my validator is in the whitelist, I unfortunatelly cannot re-delegate my funds. At the moment, I'm getting the message: "failed to execute message; message index: 0: validator does not exist". 

I should also note that my current node is running with a wallet address recovered from passphrase (that was running on my old node), and that I have taken the precaution of transfering the priv_validator_key.json file from my old machine to the new one. I have funded my node wallet successfully, and I'm only having trouble in the re-delegation procedure.  

Strangely, the explorer still shows my old balance (3,100 NGM), which was the existing amount prior to undelegation.

https://www.mintscan.io/emoney/validators/emoneyvaloper1amq83m7k9mhdd255epc68s5ucmc4tag6ywxq0p

I'd really appreciate any help from the NGM team!

**Comment by haasted** [comment]
Can you show the command you're using to create the delegation?

**Comment by nodespace1** [comment]
Sure, here it is:
emd tx staking delegate emoneyvaloper1amq83m7k9mhdd255epc68s5ucmc4tag6ywxq0p 4000000000ungm --chain-id="emoney-3" --gas="200000" --gas-prices="1ungm" --from <walletName> --keyring-backend file

Of course, <walletName> is replaced by the wallet which will be used to delegate the funds.

I also considered re-creating the validator, but upon inspection, the "emd tendermint show-validator" outputs a different emoneyvalconspub key when compared to the output of "emd keys list". Again, my current node is running data imported from the old node, so that may be a problem. Do you believe I could try re-creating the validator nonetheless?

**Comment by nodespace1** [comment]
This issue has been resolved and may be closed.
